### ISSUE TITLE
Change <ul> and <li> for <button>

### ISSUE THREAD

**Issue by milenaemmert** [ericadebem/Interactive-rating-component#1]
> We should think about change `<ul>` for buttons or radio buttons 🧐
 ```
 <ul class="pontuacao" id="nota">
    <li><a>1</a></li>
    <li><a>2</a></li>
    <li><a>3</a></li>
    <li><a>4</a></li>
    <li><a>5</a></li>
</ul>
```
The behavior that we want is more similar to a radio button, but I really think that to apply CSS in radio buttons is not a simple thing to do! So what about buttons? `<button></button>`
```
<button id="1" class="buttons">1</button>
<button id="2" class="buttons">2</button>
<button id="3" class="buttons">3</button>
<button id="4" class="buttons">4</button>
<button id="5" class="buttons">5</button>
```

> Check more about radio buttons [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio), that's the behavior we need, but we can do it with `<button>` tag and it's going to be much more easy to apply the CSS! 😊

<hr>

> In JavaScript we can add a class when the button is on click event and change its color, and use a control variable to check if the user changed the click (the note, the feedback) or not.

**Comment by ericadebem** [comment]
Good! I will do that now, thanks :)
